### ISSUE TITLE
关于实现函数range([start,]stop[,step])

### ISSUE THREAD

**Issue by jasonliao** [topview-frontend/campus-recruitment#1]
# range([start,]stop[,step])
#### 1.个人认为题目规定了stop是一定要传的, 所以参数为0的时候, 应该抛出错误

```
function range() {
    var argLength = arguments.length,
    array = [],
    i = 0,
    start = arguments[0],
    stop = arguments[1],
    step = arguments[2];
    switch(argLength) {

        case 0: 
            throw Error('至少输入一个参数,限止数组在哪里结束');

        case 1: 
            stop = arguments[0];
            for(i = 0; i < stop; i++) {
                array.push(i);
            }
            return array;
        case 2:
            for(i = start; i < stop; i++) {
                array.push(i);
            }
            return array;
        case 3:
            if(step < 1) {
                throw Error('step > 1');
            }
            for(i = start; i < stop; i+=step) {
                array.push(i);
            }
            return array;
        default : 
            throw Error('最多传入三个参数');
    }
}
```

**Comment by monkindey** [comment]
###5 你这个是不是要使用的markdown语法啦？

**Comment by jasonliao** [comment]
是呀 我都不知道为什么上面的起作用 下面的不起作用 一开始我是 ###1.的 然后 #1 这个好像变成了链接跳到了上面 # 这个这里 然后我就不知道怎么办了 : (

**Comment by monkindey** [comment]
1. **stop不一定要传**啦，range()返回的是一个[]空数组也是可以的呀，比如你用jquery $()也是发挥的是[]；
2. JSLint 你能用确实证明你对代码要求还是挺高的，但是JSLint感觉挺严格的。
3. for(var i = 0 ; i < arguments[0] ; i++) 这样子的定义i不是只是定义一次而已吗？
4. 确实**arguments**和**HTMLCollecttion**是在别人的印象中确实挺耗性能的。希望尽快贴上地址哈
5. **start > stop** 应该返回的是一个[]空数组哈，这个也是合理的呀。这个**他**也考虑了。

``` javascript
case 2 : {
   for(var i = arguments[0] ; i < arguments[1] ; i++){
      newArray.push(i);
   }
   return newArray;
   break;
 }
```

如果**arguments[0]** 比 **arguments[1]**大的话，这个循环就停了，返回**空数组[]**了

**Comment by L-movingon** [comment]
1. 如果stop可传可不传的话 那么题目不是应该[stop]吗? (个人意思而已)

**Comment by jasonliao** [comment]
1. 如果stop可传可不传 那么题目不是应该[stop]吗
   2 用来玩玩  = =
2. 一行是没有错 但是每个case里的for都var了一个i 就重复声明了
3. 在找 - - 
4. 是喔  我没有考虑到 我以为要抛个提示什么的
5. 师兄 我上面那个markdown 为什么不起作用  在issues里写markdown的时候 要写代码怎么办 一按tab就跳出这个框框了

**Comment by monkindey** [comment]
- 好吧，**stop**必须传了，问题是他下面那些例子是题目提供的还是他自己的测试例子
- 嗯，`case中的i重复定义`这个问题有待考证
- 可以看下这个[markdown basic](https://github.com/topview-frontend/chrome-devtools/issues/1)

**Comment by TimTsang** [comment]
> - 1、师弟看题目挺仔细的哈，`stop`是没有`[ ]`括起来的，`stop`是必须要传的。
> - 2、关于`JSLint`，这个的确是挺严格的，为了规范点，等下我改过来哈。
> - 3、关于`i`、`arguments`和`HTMLCollecttion`相关的性能问题,因为做的时候比较赶时间，所以没注意到，谢谢提醒哈！

**Comment by jasonliao** [comment]
谢谢师兄分享!~
